# Generated by Django 3.2.4 on 2023-01-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comparePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('uploadedImg', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('Mushroom Kits', 'Mushroom Kits'), ('Mushroom Powder', 'Mushroom Powder')], max_length=20, null=True)),
                ('tag', models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Order Created', 'Order Created'), ('Order Processing', 'Order Processing'), ('Order Ready', 'Order Ready'), ('Order Delivered', 'Order Delivered')], default='Order Created', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_type', models.CharField(choices=[('Guest', 'Guest'), ('Registered', 'Registered'), ('Registered-OTF', 'Registered-OTF')], default='Guest', max_length=20, null=True)),
                ('order_status', models.CharField(choices=[('Order Created', 'Order Created'), ('Order Processing', 'Order Processing'), ('Order Ready', 'Order Ready'), ('Order Delivered', 'Order Delivered')], default='Order Created', max_length=20, null=True)),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='S', max_length=1)),
                ('apartment_address', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qty', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.item')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
        ),
    ]
