# Generated by Django 3.2.4 on 2023-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230131_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('tinyplants', 'Tiny Plants'), ('largeplants', 'Large Plants'), ('planters', 'Planters'), ('plantcare', 'Plant Care')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, choices=[('', ''), ('featured', 'Featured')], max_length=20, null=True),
        ),
    ]
