# Generated by Django 3.2.4 on 2023-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230131_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('tinyplants', 'Tiny Plants'), ('largeplants', 'Large Plants'), ('planters', 'Planters'), ('plantcare', 'Plant Care')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, choices=[('featured', 'Featured')], default='', max_length=20, null=True),
        ),
    ]
