# Generated by Django 3.2.4 on 2023-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230204_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('Tiny Plants', 'Tiny Plants'), ('Large Plants', 'Large Plants'), ('Planters', 'Planters'), ('Plant Care', 'Plant Care')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, choices=[('', ''), ('Featured', 'Featured')], default='', max_length=20, null=True),
        ),
    ]
