# Generated by Django 3.2.4 on 2023-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20230204_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('tinyplants', 'Tiny Plants'), ('largeplants', 'Large Plants'), ('planters', 'Planters'), ('plantcare', 'Plant Care')], default='', max_length=20, null=True),
        ),
    ]
