# Generated by Django 3.2.4 on 2023-02-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('', ''), ('Tiny%20Plants', 'Tiny Plants'), ('Large%20Plants', 'Large Plants'), ('Planters', 'Planters'), ('Plant%20Care', 'Plant Care')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, choices=[('', ''), ('Featured', 'Featured'), ('Special%20Offer', 'Special Offer')], default='', max_length=20, null=True),
        ),
    ]
