# Generated by Django 3.2.4 on 2023-02-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
